name: Calculator Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: reqq
      run: pip install --no-cache-dir -r requirements.txt

    - name: rest API and test
      run: |
        python BE/calculator.py --rest &
        python -m pytest --junit-xml=report.xml
     
    - name: JUnit Report Action
      uses: mikepenz/action-junit-report@v4.3.1
      if : success()||failure()
      with:
        report_paths : '**/*.xml'

    - name: login azur
      run: |
        docker login judevops.azurecr.io -u ${{secrets.USERNAME}} -p ${{secrets.PASSWORD}}
       

    - name: build and push
      run: |
        docker build -t judevops.azurecr.io/eyad-calculator ./BE
        docker push judevops.azurecr.io/eyad-calculator
