name: Calculator Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: login azur
      run: |
        docker login judevops.azurecr.io -u ${{secrets.USERNAME}} -p ${{secrets.PASSWORD}}
       

    - name: Print Hello
      run: |
        docker build -t judevops.azurecr.io/eyad-calculator ./BE
        docker push judevops.azurecr.io/eyad-calculator
